import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Vazirmatn } from "next/font/google";
import Header from "@/components/common/Header/Header";
import Footer from "@/components/common/Footer/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const vazir = Vazirmatn({
  subsets: ["latin"],
  weight: '400',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <div className="px-8 pt-6">
        <Header />
      </div>


      <body
        className={vazir.className}

      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
      <div className="px-8 pb-8">
        <Footer />
      </div>
    </html>
  );
}
