import "./globals.css";
import { Vazirmatn } from "next/font/google";
import HideHeaderFooter from "@/components/HideHeaderFooter";
import { Metadata } from "next";

const vazir = Vazirmatn({
  subsets: ["latin"],
  weight: "400",
});
export const metadata: Metadata = {
  title: "Delta Platform",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <body className={`${vazir.className} bg-[#232323]`}>
        <div className=" flex flex-col ">
          <HideHeaderFooter>{children}</HideHeaderFooter>
        </div>
      </body>
    </html>
  );
}
