import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Vazirmatn } from "next/font/google";
import Header from "@/components/common/Header/Header";
import Footer from "@/components/common/Footer/Footer";
// import ClientProviders from "@/components/ClientProviders";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const vazir = Vazirmatn({
  subsets: ["latin"],
  weight: '400',
})

export const metadata: Metadata = {
  title: "Delta Platform",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body className={vazir.className}>
        <div className="min-h-screen flex flex-col ">
          <header className="px-8 pt-6 ">

            <Header />
          </header>

          {/* <ClientProviders> */}
            <main className="flex-1">
              {children}
            </main>
          {/* </ClientProviders> */}

          <footer className="px-8 pb-8 pt-[100px]">
            <Footer />
          </footer>
        </div>
      </body>
    </html>
  )
}

